# Generated by Django 3.2.9 on 2021-11-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_topping_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
