# Generated by Django 3.2.9 on 2021-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
